// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtZdsFEiEJdYmFomcitytTVQ7ICtaIds0',
    appId: '1:552200408711:web:920a31595242da23c77222',
    messagingSenderId: '552200408711',
    projectId: 'darebny-42086',
    authDomain: 'darebny-42086.firebaseapp.com',
    storageBucket: 'darebny-42086.appspot.com',
    measurementId: 'G-HLMK4DX0SK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbXJdwiDgUId8Yhk--XYoc0bzJ4RRkvf4',
    appId: '1:552200408711:android:f6700b45d1b28d90c77222',
    messagingSenderId: '552200408711',
    projectId: 'darebny-42086',
    storageBucket: 'darebny-42086.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkbIIIbgbFiYPAPtM706feU5NC3a7UAD8',
    appId: '1:552200408711:ios:df17ff69992b78fac77222',
    messagingSenderId: '552200408711',
    projectId: 'darebny-42086',
    storageBucket: 'darebny-42086.appspot.com',
    iosClientId: '552200408711-f5endk04getvb7ohtdlmpcbnekl1hf1c.apps.googleusercontent.com',
    iosBundleId: 'com.example.darebny',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkbIIIbgbFiYPAPtM706feU5NC3a7UAD8',
    appId: '1:552200408711:ios:df17ff69992b78fac77222',
    messagingSenderId: '552200408711',
    projectId: 'darebny-42086',
    storageBucket: 'darebny-42086.appspot.com',
    iosClientId: '552200408711-f5endk04getvb7ohtdlmpcbnekl1hf1c.apps.googleusercontent.com',
    iosBundleId: 'com.example.darebny',
  );
}
